### ISSUE TITLE
Fails to find settings file

### ISSUE THREAD

**Issue by dlecocq** [outlyerapp/dlcli#3]
From a clean install, it appears that the `save_setting` function invoked in the `set` subcommand is unhappy:

```
$ dlcli set org moz
Traceback (most recent call last):
  File "/vagrant/venv/bin/dlcli", line 11, in <module>
    sys.exit(main())
  File "/vagrant/venv/lib/python2.7/site-packages/dlcli/dlcli.py", line 5, in main
    cli(obj={"filters": []})
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vagrant/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/vagrant/venv/lib/python2.7/site-packages/dlcli/cli/set.py", line 23, in org
    save_setting(setting={"org": str(org)}, **context.settings)
  File "/vagrant/venv/lib/python2.7/site-packages/dlcli/api/utils.py", line 56, in save_setting
    with open(settings_file, 'w') as yaml_file:
IOError: [Errno 2] No such file or directory: ''
```

**Comment by sacreman** [comment]
This should be fixed by https://github.com/dataloop/dlcli/commit/88bb1971cc5bd6c1156ea754378a14a37cdd2a78
