### ISSUE TITLE
Display error message and cancel operation to set account to invalid name.

### ISSUE THREAD

**Issue by DevOpsDave** [outlyerapp/dlcli#5]
Whenever I set my account to a bogus account name (on accident of course) I think the tool should immediately give me an error and cancel the operation to set the tool to the bogus state.  Right now this is what happens.  I set my account to 'blah':

``` bash
$ ❯❯❯ dlcli set account blah
$ ❯❯❯ dlcli status | grep -v Key
URL: https://app.dataloop.io/api/v1/orgs/desk/accounts
Organization: desk
Account: blah
Authenticated: True
$ ❯❯❯ dlcli get dashboards
Traceback (most recent call last):
  File "/usr/local/bin/dlcli", line 9, in <module>
    load_entry_point('dlcli==0.0.39', 'console_scripts', 'dlcli')()
  File "/Library/Python/2.7/site-packages/dlcli/dlcli.py", line 5, in main
    cli(obj={"filters": []})
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/dlcli/cli/get.py", line 37, in dashboards
    for dashboard in Dashboards(ctx).get_dashboards():
  File "/Library/Python/2.7/site-packages/dlcli/api/dashboards.py", line 17, in get_dashboards
    headers=self.headers).json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I discovered this originally when I had set my account to "pord" and not "prod".  It took me a few minutes to figure out the issue since the error message did not tell me what the real issue was.

**Comment by sacreman** [comment]
Hi, I've updated the `dlcli status` command to pull back from the account name so it will 404 with a red error if the url, org or account are set wrong. It should 401 error with a red message if the key is wrong.

For the commands I've gone through and wrapped the stack traces in some broad exception handing that should still print out the problem. I need to go through the API and raise better messages for different exception types but https://github.com/dataloop/dlcli/commit/4e43962c1ba90576e338427eda6f2b69cae06ae5 should be an improvement over no exception handling.
